# Generated by Django 2.2.12 on 2020-05-13 03:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200512_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_alt',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
